simple_checklist_project/simpleChecklist/urls.py
from django.conf.urls import url
from simpleChecklist import views


urlpatterns = [
    # The main four URLs that show what I intend the user to see
    url(r'^$', views.index, name='index'),
    url(r'^create_todolist/$', views.create_todolist, name='create_todolist'),
    url(r'^todolist/(?P<user_name>[\w.@+-]+)/(?P<todolist_name_slug>[\w\-]+)/$', views.todolist, name='todolist'),
    url(r'^todolist/(?P<user_name>[\w.@+-]+)/(?P<todolist_name_slug>[\w\-]+)/create_task/$', views.create_task, name='create_task'),
    # These three URLs don't have actual templates of their own. Instead they work off of the Index and Todolist templates
    url(r'^delete_todolist/$', views.delete_todolist, name="delete_todolist"),
    url(r'^delete_task/$', views.delete_task, name="delete_task"),
    url(r'^sort_tasks/$', views.sort_tasks, name="sort_tasks"),
]

simple_checklist_project/simple_checklist_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from registration.backends.simple.views import RegistrationView

# After registering an account, redirects the user to the home page,
# instead of django-registration-redux's default registration success page
class AltRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return '/simple-checklist/'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^simple-checklist/', include('simpleChecklist.urls')),
    url(r'^accounts/register/$', AltRegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
]

simple_checklist_project/simpleChecklist/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from django.template.defaultfilters import slugify
from datetime import datetime
from django.contrib.auth.models import User

# TodoLists are here to contain Tasks. When making one, the user can only control the Name field.
# TodoLists also have a User field, which is the user that created it. I use this to prevent
# users from editing other users' lists.
class TodoList(models.Model):
    # After testing with capital Ws, I can fit about 35 characters in the name field
    name = models.CharField(max_length=35)
    # Just a normal slug field to help make the URL
    slug = models.SlugField()

    created_on = models.DateField(auto_now_add=True)
    user = models.ForeignKey(User, default='')

    def save(self, *args, **kwargs):
        if len(self.name) > 35:
            self.name = self.name[:35]

        self.slug = slugify(self.name)
        super(TodoList, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.name

    # With the name and user fields set to be unique in combination,
    # multiple todolists with the same name can be made by different users,
    # but multiple todolists with the same name can't be made by the same user.
    class Meta:
        unique_together = (("name", "user"),)

# Tasks are the actual content of the TodoLists. Aside from a Name, they have a Due Date
# (any date, even in the past), Priority (Low, Medium or High), and a Note (any extra text the user wants)
class Task(models.Model):
    # one-to-many relationship with TodoLists set up here
    todolist = models.ForeignKey(TodoList)
    name = models.CharField(max_length=35)
    slug = models.SlugField()

    note = models.TextField(max_length=40)
    date = models.DateField(blank=False, default=datetime.now)
    created_on = models.DateField(auto_now_add=True)

    LOW = "1"
    NORMAL = "2"
    HIGH = "3"
    PRIORITY_CHOICES = (
        (LOW, 'Low'),
        (NORMAL, 'Normal'),
        (HIGH, 'High'),
    )
    priority = models.CharField(
        max_length=1,
        choices=PRIORITY_CHOICES,
        default=NORMAL,
    )

    def save(self, *args, **kwargs):
        if len(self.name) > 35:
            self.name = self.name[:35]

        if len(self.note) > 40:
            self.note = self.note[:40]

        self.slug = slugify(self.name)
        super(Task, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.name

simple_checklist_project/simpleChecklist/forms.py
from django import forms
from simpleChecklist.models import TodoList, Task

class TodoListForm(forms.ModelForm):
    name = forms.CharField(max_length=128)
    slug = forms.CharField(widget=forms.HiddenInput, required=False)

    class Meta:
        model = TodoList
        fields = ['name']

class TaskForm(forms.ModelForm):
    name = forms.CharField(max_length=128)
    slug = forms.CharField(widget=forms.HiddenInput, required=False)
    note = forms.CharField(widget=forms.Textarea, max_length=200, required=False)
    PRIORITY_CHOICES = (
        ('1', 'Low'),
        ('2', 'Normal'),
        ('3', 'High'),
    )
    priority = forms.ChoiceField(choices=PRIORITY_CHOICES, initial="2")

    class Meta:
        model = Task
        widgets = {
            'date': forms.DateInput(attrs={'type':'date'})
        }
        exclude = ['todolist']

simple_checklist_project/simpleChecklist/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect

from simpleChecklist.models import TodoList, Task
from simpleChecklist.forms import TodoListForm, TaskForm

from django.contrib.auth.decorators import login_required

from django.utils.datastructures import MultiValueDictKeyError
from django.http import HttpResponse

@login_required
def index(request):

    # Queries the database for all of a user's Todo Lists
    todolist_list = TodoList.objects.filter(user=request.user)

    return render(request, 'simpleChecklist/index.html', {'todolists': todolist_list})

@login_required
def todolist(request, todolist_name_slug, user_name):

    context_dict = {}
    # Gathers all of the tasks' info for the todolist with the given slug,
    # to return as the context
    try:
        todolist = TodoList.objects.get(slug=todolist_name_slug, user=request.user)
        context_dict['todolist_name'] = todolist.name

        # Orders all of the tasks in the given todo list by their due date
        tasks = Task.objects.filter(todolist=todolist)
        context_dict['tasks'] = tasks

        # Used in the template to check whether the todolist exists or not
        context_dict['todolist'] = todolist

        # The username and slug are here to identify the specific todolist,
        # and are combined to make a unique URL.
        context_dict['user_name'] = user_name
        context_dict['todolist_name_slug'] = todolist_name_slug


    except TodoList.DoesNotExist:
        # There's no need to check whether the TodoList exists twice,
        # so I stop that error from raising an exception here.
        pass

    return render(request, 'simpleChecklist/todolist.html', context_dict)

@login_required
# Loads the todo list form from forms.py on GET, saves form info to the todo list data on POST
def create_todolist(request):

    if request.method == 'POST':
        form = TodoListForm(request.POST)

        if form.is_valid():
            todolist = form.save(commit=False)
            todolist.user = request.user
            todolist.save()
            # When a todolist is successfully created, redirects to the page that displays them all
            return redirect(index)

        else:
            print form.errors

    else:
        form = TodoListForm()

    return render(request, 'simpleChecklist/create_todolist.html', {'form': form})

# Basically the same as create_todolist, except with a couple of extra arguments to
# filter out the todo list being added to, and to provide info for the todo list template after
# successfully filling out the form
@login_required
def create_task(request, todolist_name_slug, user_name):

    try:
        currentList = TodoList.objects.get(slug=todolist_name_slug, user=request.user)
    except TodoList.DoesNotExist:
        currentList = None

    if request.method == 'POST':
        form = TaskForm(request.POST)

        if form.is_valid():
            if currentList:
                task = form.save(commit=False)
                task.todolist = currentList
                task.save()
                # Makes sure the todolist template has all the info it needs
                return redirect(todolist, todolist_name_slug=todolist_name_slug, user_name=request.user)

        else:
            print form.errors

    else:
        form = TaskForm()

    context_dict = {'form': form, 'todolist': currentList}
    return render(request, 'simpleChecklist/create_task.html', context_dict)


@login_required
def delete_todolist(request):
    context_dict = {}
    # I use a try/except statement here just in case some sneaky user decides to type in the URL manually
    # on the wrong page. Since this view doesn't have its own template, that causes errors.
    try:
        # How this data gets here:
        # data-listid (index template) -> listid (javascript) -> list_id (request)
        list_id = request.GET['list_id']

    except MultiValueDictKeyError:
        error_type = "Bad URL"
        context_dict['error_type'] = error_type

        error_message = "Did you get here on accident? Try going back to the home page."
        context_dict['error_message'] = error_message

        return render(request, 'simpleChecklist/error.html', context_dict)

    except UnboundLocalError:
        error_type = "Bad URL"
        context_dict['error_type'] = error_type

        error_message = "Something went horribly wrong with the URL. Go back to the home page and try again."
        context_dict['error_message'] = error_message

        return render(request, 'simpleChecklist/error.html', context_dict)

    # This 'should' always be true, since the delete buttons are hidden whenever their lists are
    if list_id:
        todolist = TodoList.objects.get(id=list_id)
        todolist.delete()

    # If something goes horribly wrong, sends the user back to the homepage before doing anything
    else:
        return redirect(index)

    # Lines up the context with what the original index page template displays, with
    # the deleted list now gone
    todolist_list = TodoList.objects.filter(user=request.user)
    context_dict['todolists'] = todolist_list

    # Sends template info to an alternate template, index_alt, which holds HTML
    # for the jQuery to load into the original template
    return render(request, 'simpleChecklist/index_alt.html', context_dict)

# Pretty much a rehash of the delete_todolist function, except it grabs the deleted task's
# todo list id in order to update the template's task list after a task is deleted
@login_required
def delete_task(request):
    context_dict = {}
    try:
        task_id = request.GET['task_id']
    except MultiValueDictKeyError:
        error_type = "Bad URL"
        context_dict['error_type'] = error_type

        error_message = "Did you get here on accident? Try going back to the home page."
        context_dict['error_message'] = error_message

        return render(request, 'simpleChecklist/error.html', context_dict)

    except UnboundLocalError:
        error_type = "Bad URL"
        context_dict['error_type'] = error_type

        error_message = "Something went horribly wrong with the URL. Go back to the home page and try again."
        context_dict['error_message'] = error_message

        return render(request, 'simpleChecklist/error.html', context_dict)

    if task_id:
        list_id = request.GET['list_id']

        if list_id:
            task = Task.objects.filter(id=task_id)
            task.delete()
            todolist = TodoList.objects.filter(id=list_id)[0]
            context_dict['todolist'] = todolist
            # Finds the new list of tasks here
            tasks = Task.objects.filter(todolist=todolist)
            context_dict['tasks'] = tasks

        else:
            return redirect(index)

    else:
        return redirect(index)

    return render(request, 'simpleChecklist/todolist_alt.html', context_dict)

# Sorts the task table by whatever data-sorttype specifies, with no need for branching if statements
def sort_tasks(request):
    context_dict = {}
    try:
        list_id = request.GET['list_id']

    except MultiValueDictKeyError:
        error_type = "Bad URL"
        context_dict['error_type'] = error_type

        error_message = "Did you get here on accident? Try going back to the home page."
        context_dict['error_message'] = error_message

        return render(request, 'simpleChecklist/error.html', context_dict)

    sort_type = request.GET['sort_type']


    if list_id and sort_type:
        todolist = TodoList.objects.filter(id=list_id)[0]
        context_dict['todolist'] = todolist

        tasks = Task.objects.filter(todolist=todolist).order_by(sort_type)
        context_dict['tasks'] = tasks

    else:
        return redirect(index)

    return render(request, 'simpleChecklist/todolist_alt.html', context_dict)

simple_checklist_project/templates/simpleChecklist/create_task.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}New Task{% endblock %}

{% block body_block %}
  <script src="{% static 'js/formlabels.js' %}"></script>
  {% if user.is_authenticated %}
  <div class="contentBox">
    <h1>Create a new task</h1>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
    $(function () {
      $("#id_date").datepicker();
    });
    </script>
    <form action="." method="POST">

      {% csrf_token %}
      {% for hidden in form.hidden_fields %}
        {{ hidden }}
      {% endfor %}

      {% for field in form.visible_fields %}
        {{ field.errors }}
        {{ field.help_text }}
        <p>{{ field }}</p>
      {% endfor %}

      <input type="submit" name="submit" value="Submit Task" />
    </form>

  {% else %}
    <a href="{% url 'registration_register' %}">Sign Up<a> or <a href="{% url 'auth_login' %}">Log In</a> to create tasks.
  {% endif %}
</div>
{% endblock %}

simple_checklist_project/templates/simpleChecklist/create_todolist.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}New List{% endblock %}

{% block body_block %}
  <script src="{% static 'js/formlabels.js' %}"></script>
  <div class="contentBox">
  {% if user.is_authenticated %}

    <h1>Create a new list</h1>

    <form action="." method="POST">

      {% csrf_token %}
      {% for hidden in form.hidden_fields %}
        {{ hidden }}
      {% endfor %}

      {% for field in form.visible_fields %}
        {{ field.errors }}
        {{ field.help_text }}
        {{ field }}
      {% endfor %}

      <p><input type="submit" name="submit" value="Create List" /></p>
    </form>

  {% else %}
    <a href="{% url 'registration_register' %}">Sign Up<a> or <a href="{% url 'auth_login' %}">Log In</a> to create lists.
  {% endif %}
</div>
{% endblock %}

simple_checklist_project/templates/simpleChecklist/error.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Error{% endblock %}

{% block body_block %}
  <h1>Error: {{ error_type }}</h1>
  
  <div class="contentBox">
    {{ error_message }}
  </div>
{% endblock %}

simple_checklist_project/templates/simpleChecklist/index.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block body_block %}
  <h1>Hello, <strong>{{ user.username }}</strong>!</h1>

  <div class="contentBox">
  {% if todolists %}
    <div id="lists">
    <ul>
      {% for todolist in todolists %}
        <li class="todolist">
          {{ todolist.created_on }} |
          <a class="listName" href="{% url 'todolist' todolist.user todolist.slug %}">{{ todolist.name }}</a>
          <span class="deleteList" data-listid="{{ todolist.id }}"></span>
        </li>
      {% endfor %}
    </ul>
    </div>
  {% else %}
    <strong>You don't have any lists.</strong>
  {% endif %}
    <a class="textlink" href="{% url 'create_todolist' %}">Create a List</a><br />
  </div>
{% endblock %}

simple_checklist_project/templates/simpleChecklist/index_alt.html
{% load staticfiles %}

<script src='https://code.jquery.com/jquery-3.2.1.min.js'></script>
<script src='{% static "js/simpleChecklist-jQuery.js" %}'></script>

{% if todolists %}
  <div id="lists">
    <ul>
      {% for todolist in todolists %}
      <li class="todolist">
        {{ todolist.created_on }} |
        <a class="listName" href="{% url 'todolist' todolist.user todolist.slug %}">{{ todolist.name }}</a>
        <span class="deleteList" data-listid="{{ todolist.id }}"></span>
      </li>
      {% endfor %}
    </ul>
  </div>
{% else %}
  <strong>You don't have any lists.</strong>
{% endif %}

simple_checklist_project/templates/simpleChecklist/todolist.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}{{ todolist_name }}{% endblock %}

{% block body_block %}
  {% if user.is_authenticated %}
    {% if todolist %}
    <h1>{{ todolist_name }}</h1>
    <div class="contentBox">
      {% if tasks %}
        <div id="tasks">

          <span class="sortLabel">sort by:</span>
          <span class="sortLabel">due date</span>
          <span class="sort asc" data-listid="{{ todolist.id }}" data-sorttype="date"></span>
          <span class="sort desc" data-listid="{{ todolist.id }}" data-sorttype="-date"></span>
          <span class="sortLabel">priority</span>
          <span class="sort asc" data-listid="{{ todolist.id }}" data-sorttype="priority"></span>
          <span class="sort desc" data-listid="{{ todolist.id }}" data-sorttype="-priority"></span>

          <table>
            {% for task in tasks %}
              <tr class="task">
                <td class="taskInfo">{{ task.date }} | {{ task.name }}, priority: {{ task.get_priority_display }}
                </td>
                <td class="deleteButton">
                <span class="deleteTask" data-listid="{{ todolist.id }}" data-taskid="{{ task.id }}"></span>
                </td>
              </tr>
              <tr class="note">
                <td class="taskNote"><strong>-</strong> {{ task.note }}</td>
              </tr>
            {% endfor %}
          </table>
        </div>
      {% else %}
        <strong>No tasks currently in todolist.</strong>
      {% endif %}

      <a class="textlink" href="{% url 'create_task' todolist.user todolist.slug %}">Create a Task</a><br />
    {% else %}
      <p>You can't access this list.</p>
    {% endif %}
  </div>
  {% else %}
    <a href="{% url 'registration_register' %}">Sign Up<a> or <a href="{% url 'auth_login' %}">Log In</a> to see lists.
  {% endif %}
{% endblock %}

simple_checklist_project/templates/simpleChecklist/todolist_alt.html
{% load staticfiles %}

<script src='https://code.jquery.com/jquery-3.2.1.min.js'></script>
<script src='{% static "js/simpleChecklist-jQuery.js" %}'></script>

{% if tasks %}
<div id="tasks">

  <span class="sortLabel">sort by:</span>
  <span class="sortLabel">due date</span>
  <span class="sort asc" data-listid="{{ todolist.id }}" data-sorttype="date"></span>
  <span class="sort desc" data-listid="{{ todolist.id }}" data-sorttype="-date"></span>
  <span class="sortLabel">priority</span>
  <span class="sort asc" data-listid="{{ todolist.id }}" data-sorttype="priority"></span>
  <span class="sort desc" data-listid="{{ todolist.id }}" data-sorttype="-priority"></span>

  <table>
    {% for task in tasks %}
      <tr class="task">
        <td class="taskInfo">{{ task.date }} | {{ task.name }}, priority: {{ task.get_priority_display }}
        </td>
        <td class="deleteButton">
        <span class="deleteTask" data-listid="{{ todolist.id }}" data-taskid="{{ task.id }}"></span>
        </td>
      </tr>
      <tr class="note">
        <td class="taskNote"><strong>-</strong> {{ task.note }}</td>
      </tr>
    {% endfor %}
  </table>
</div>
{% else %}
  <strong>No tasks currently in todolist.</strong>
{% endif %}